name: Docker Build Validation

on:
  pull_request:
    branches: [main]

jobs:
  test-docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            -t mem0_api:test \
            -f deployment/Dockerfile \
            .
